[package]
name = "decode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "1.0.136"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
miniz_oxide = "0.5.3"

yata = "0.6"

crypto-crawler = "4.3.4"
crypto-markets = "1.2.5"
crypto-market-type = "1.1.0"
crypto-msg-parser = "2.2.7"
crypto-msg-type = "1.0.6"
crypto-pair = "2.2.7"
crypto-rest-client = "0.9.0"
crypto-ws-client = "4.11.3"
tokio = { version = "1.18.2", features = ["macros", "rt-multi-thread", "sync", "time"] }
chrono = "0.4.19"
rust_decimal = "1.23.1"
rust_decimal_macros = "1.23.1"
